version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - main
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
      - postgres
    networks:
      - main

  redis:
    image: redis:7
    container_name: sibgar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - main

volumes:
  postgres_data:
  redis-data:
  app:

networks:
  main: