# Generated by Django 5.0.2 on 2024-02-22 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
